### ISSUE TITLE
Layer 3 "|" key types ">"

### ISSUE THREAD

**Issue by ecopsychologer** [ZitaoTech/BB9900-USB_BLE_Keyboard#1]
as said above, I noticed the keyboard can't type the pipe key. I really love how well y'all have mapped this out. I'll look and see if I can make a fork and fix it myself when I have the time but wanted you to know about this issue. Thanks so much for your work, I love the keyboard despite this!

**Comment by ZitaoTech** [comment]
Hi, I did some tests. If I shift the keyboard layout in system to English. The "|" key in layer 3 will output "|". 
If I type in German keyboard layout, it does output ">", not "|".
Did you type this key in German or other language in keyboard layout in your system? There will be different output even the device receives the same keycode from the keyboard.

**Comment by ecopsychologer** [comment]
Interesting! I think it should be English as I only really type English but I'll see what it's set to and report back. I’m gonna do a remap anyways and found your awesome tool (thank you for making that) because I think I need a ~ since I use it with my raspberry pi and steam deck to type in the console. Regardless, amazing work. It looks and feels great! And rad to know I can print a new case if I crack it or something!

**Comment by ecopsychologer** [comment]
So I had two keyboards, one English and one Spanish, probably because I had a Spanish keyboard on my phone. I deleted that, but instead of a pipe now I get this ± lol, my keyboard is set to "U.S." thanks for the help, I may just need to remap it...

**Comment by ecopsychologer** [comment]
@ZitaoTech hey all good if you don't know this but while I have you in a thread, do you think it'd be possible for me to program the board so that if I am sliding my finger from one side of the trackpad to the other and then hold it on the edge of the trackpad it could keep going? Not asking you to program it, I would be more than happy to do the work to get my keyboard doing that, I’m just curious if you think it's within the bounds of the technology given what it's made on? I know the board is pro micro like which is pretty capable but I don't know what the interface is like... I'll be diving in deeper later today but I figured I would ask. Thanks for your time and all your help!

**Comment by ZitaoTech** [comment]
@ecopsychologer 

It seems it's not possible. The trackpad is like most of the mouse sensors, it can only detect a relative movement of your finger or something above the surface. The sensor can't know the absolute position of your finger, so it can't know whether your finger on the edge or not.

You can also view the datasheet of the sensor in this link: https://github.com/ZitaoTech/BB9900-USB-keyboard/blob/main/Docs/Avago-ADBS-A320-datasheet.pdf

**Comment by ecopsychologer** [comment]
Ahhh I don't know why I didn't imagine it was this kind of sensor. Thanks anyways! I think/hope all my problems will be over once I remap. I really appreciate all your help!
